# Generated by Django 3.1.1 on 2020-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fine',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
