# Generated by Django 3.1.1 on 2020-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0003_auto_20201029_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(),
        ),
    ]
